// Generated by CoffeeScript 2.2.4
var redisStore, session;

session = require('koa-generic-session');

redisStore = require('koa-redis');

module.exports = session({
  store: awesome.redis ? redisStore(awesome.config.redis) : void 0
});
