// Generated by CoffeeScript 2.2.4
module.exports = {
  getExample: async function() {
    var example;
    example = (await awesome.models.ExampleModel.where({}).fetch());
    return example.toJSON();
  }
};
